### ISSUE TITLE
Not Working in Ubuntu 20.04

### ISSUE THREAD

**Issue by madaky** [giacmir/Inkscape-JPEG-export-extension#26] opened 2020-04-29 18:34 UTC
I just tried this extension in new Ubuntu release as snap version and without snap version. In both scenario not able to get output  file.

**Comment by giacmir** [comment] 2020-06-30 08:43
Hello @madaky , which version of inkscape are you using?

**Comment by Moini** [comment] 2020-06-30 11:22
This is to be expected, as the extension hasn't been updated to work with Inkscape 1.0. Suggest closing this as a duplicate of https://github.com/giacmir/Inkscape-JPEG-export-extension/issues/25 .

**Comment by Moini** [comment] 2020-06-30 11:24
Or... not yet. Sorry. The snap is 1.0, the version from the repositories via deb is 0.92.5. That one should still work. The AppImage is 1.0, the flatpak is 1.0. The ppa version is 1.0.

**Comment by madaky** [comment] 2020-06-30 13:35
@giacmir: using 1.0 (1.0+r73+1)

**Comment by giacmir** [comment] 2020-06-30 13:45
Thank you @madaky 
this extension is not (yet?) compatible with 1.0 as Inkscape reworked their extension API. At the moment I don't have free time to work on this, so I can't give you an ETA for 1.0 compatibility.

I'm closing this as a duplicate of #25

**Closed by giacmir** 2020-06-30 13:45 UTC
