### ISSUE TITLE
Not exporting

### ISSUE THREAD

**Issue by brdcampos** [giacmir/Inkscape-JPEG-export-extension#6] opened 2015-11-24 10:58 UTC
Hi Giacomo,

I'm using Inkscape 0.91 and ImageMagick-6.9.2-6-Q16-x64. The SO is Windows 7.

When I try to export JPEG it seems to process the image but it does not generate an JPEG output.

![unnamed](https://cloud.githubusercontent.com/assets/15997420/11364742/6e32184e-9289-11e5-80cd-c38d8031d78e.png)
![unnamed1](https://cloud.githubusercontent.com/assets/15997420/11364744/732607fc-9289-11e5-9f09-ed3d0273bdb0.png)
![unnamed2](https://cloud.githubusercontent.com/assets/15997420/11364747/7538228c-9289-11e5-9369-91f122e0d7aa.png)

What could be going wrong?

**Comment by giacmir** [comment] 2015-11-24 11:24
Hi, can you try to manually launch a convert command on a png created by inkscape and tell me if it works?

Something like `convert -quality 100 -density 90 source.png destination.jpg`

If there is any error output please post it here.

**Comment by brdcampos** [comment] 2015-11-24 11:31
There is no error.

It is simply not exporting.

**Comment by giacmir** [comment] 2015-11-24 11:47
Have you tried running the above command from shell? I suspect there something wrong with imagemagick.

**Comment by brdcampos** [comment] 2015-11-24 11:50
No,

I don't know how to do that :D 

Would you please show me how?

**Comment by giacmir** [comment] 2015-11-24 12:14
Open the command prompt, go to a folder where you have some images and type the above command (changing filenames of course). Post the output.

**Comment by brdcampos** [comment] 2015-11-24 12:30
Yes,

It worked! Thank you

The question now is: Why this is not working when I try it with the
Inkscape?

2015-11-24 10:14 GMT-02:00 Giacomo Mirabassi <notifications@github.com>:

> Open the command prompt, go to a folder where you have some images and
> type the above command (changing filenames of course). Post the output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giacmir/Inkscape-JPEG-export-extension/issues/6#issuecomment-159249973>
> .
>



-- 
Bruno de Campos

**Comment by giacmir** [comment] 2015-11-24 14:51
What settings are you passing to the plugin? (quality, density, ... )

**Comment by brdcampos** [comment] 2015-11-24 15:05
Quality 100%
Background color: #ffffff
Density: 90
Export the whole page: checked

**Comment by giacmir** [comment] 2015-11-24 15:08
Try removing the % sign for quality.

**Comment by brdcampos** [comment] 2015-11-24 15:08
It is removed

**Comment by brdcampos** [comment] 2015-11-24 15:11
![config](https://cloud.githubusercontent.com/assets/15997420/11370882/ce1df6ce-92ac-11e5-92ee-adda0112e343.png)

**Comment by giacmir** [comment] 2015-11-24 15:13
Does the error appears with the "export whole page" option checked?

**Comment by brdcampos** [comment] 2015-11-24 15:16
Yes,

In both cases "Export whole page" and "Fast export (suggested)" the error persist.

Nothing happen when I try to export.

**Comment by Moini** [comment] 2015-12-13 19:09
@brdcampos : also look into your folder for temporary files (which, according to the extension, is C:\\WINDOWS\\Temp\\ - but might well not exist). 
The extension is supposed to write a png file of the name jpinkexp.png into it. 
Is there a png file created? Do you have a directory of that name?

**Comment by zachleigh** [comment] 2016-02-01 13:36
Doesnt work here either.
```
Traceback (most recent call last):
  File "jpegexport.py", line 185, in <module>
    _main()
  File "jpegexport.py", line 181, in _main
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 265, in affect
    self.getposinlayer()
  File "/usr/share/inkscape/extensions/inkex.py", line 207, in getposinlayer
    x = self.unittouu( xattr[0] + 'px' )
  File "/usr/share/inkscape/extensions/inkex.py", line 351, in unittouu
    return retval * (self.__uuconv[u.string[u.start():u.end()]] / self.__uuconv[self.getDocumentUnit()])
  File "/usr/share/inkscape/extensions/inkex.py", line 326, in getDocumentUnit
    svgunitfactor = self.__uuconv[svgwidthunit] * width / viewboxwidth
ZeroDivisionError: float division by zero
```
It freezes Inkscape completely. Ubuntu 14.10.

**Comment by giacmir** [comment] 2016-02-01 13:49
Thanks @zachleigh, i'm not sure this is the same issue reported by @brdcampos but I will track here both for now. In your case the "export whole page" and, I think, even the "slow export" options should still work, as they don't call those functions.

Perhaps is something related to [this bug](https://bugs.launchpad.net/inkscape/+bug/1474188).

I will take a look on that as soon as possible.

**Comment by Moini** [comment] 2016-02-01 16:03
Yep, that's most probably the correct Inkscape bug. In the patch suv made, a percentage value (100%) is used instead of the viewbox width. Don't know if that could work as a fallback here, too, somehow? 
See https://launchpadlibrarian.net/222922244/1474188+1508400-extensions-support-drawing-scale-v2.diff

(or you could just override the old functions by the new ones in the patch)

**Comment by su-v** [comment] 2016-02-01 21:43
@Moini - jfyi, that diff is outdated and won't apply to stable Inkscape 0.91 (it was not targeted for 0.91.x) nor to current trunk (due to a later commit by someone else which broke it). The report the diff was attached to was later linked to a merge proposal with latest updates.

**Comment by su-v** [comment] 2016-02-01 22:52
@zachleigh - can you share the SVG file which triggers the error? Or at least test on your system whether other extensions (e.g. 'Extensions > Render > Gear > Gear ...') work as expected with that specific SVG file? I suspect other extensions will fail with the same error ...

What strikes me as rather odd is your last sentence about Inkscape itself freezing completely after the externally spawned python process returns a traceback (just text) via stderr to inkscape. Can't recall having encountered such a freeze (at least not based on what appears to be rather trivial early-on script failure due to possibly bogus data in the SVG file (likely the ```viewBox``` width is zero - which disables displaying the content of the drawing in any SVG viewer (≠ SVG editor)).

@giacmir - every extension which imports ```inkex.py```, and uses an instance of the ```Effect()``` class along with overriding the ```effect()``` method will call ```getposinlayer()``` before even running ```effect()``` (it's called in [```affect()```](https://bazaar.launchpad.net/~inkscape.dev/inkscape/RELEASE_0_91_BRANCH/view/head:/share/extensions/inkex.py#L265) which is rarely overridden by extension scripts (```affect()``` parses all options, sets up the document, prepares the lists of selected objects, etc. before it finally calls ```effect()```), and AFAICT not by yours either).

**Comment by giacmir** [comment] 2016-02-20 08:25
I found some time for testing today, but can't reproduce the bug. I tried exporting different object types and shapes, single points tracks, object with masks and so on. 

@zachleigh It could be very useful if you can attach a svg files that gives you the error.

**Comment by giacmir** [comment] 2016-08-26 12:22
No answer in six months, closing.

**Closed by giacmir** 2016-08-26 12:22 UTC

**Comment by owen9825** [comment] 2017-09-23 22:15
[horizontal-bar.svg.zip](https://github.com/giacmir/Inkscape-JPEG-export-extension/files/1326909/horizontal-bar.svg.zip)
When I try to save this image as an optimised SVG, it has that same error about dividing by zero that was mentioned by @zachleigh

**Comment by giacmir** [comment] 2017-09-24 15:49
thanks @owen9825 ,
this seems to be a bug in the inkscape core inkex library. It seems that there is a situation where `viewboxwidth` is not defined and thus we got a division by zero.

The bug report at inkscape is from 2015 and still marked "in progress" https://bugs.launchpad.net/inkscape/+bug/1474188
